### ISSUE TITLE
native plugins issues

### ISSUE THREAD

**Issue by abdallah-odeh** [huynguyennovem/flutter-add-to-app-ios-swiftui#1]
Hello @huynguyennovem 
thank you so much for the blog & repo about this topic

I have an already made app & I want to take a feature from it and convert it into a module to be able to use in other apps (Native & Flutter) apps
this feature contains some native libraries such as **device_info_plus**
when I run the module alone, it works perfectly fine, but when I run the iOS app and press "Open Flutter View" and get the deviceId it throws an exception
```
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method getDeviceInfo on channel dev.fluttercommunity.plus/device_info)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:308:7)
<asynchronous suspension>
#1      MethodChannelDeviceInfo.deviceInfo (package:device_info_plus_platform_interface/method_channel/method_channel_device_info.dart:19:10)
<asynchronous suspension>
#2      DeviceInfoPlugin.iosInfo (package:device_info_plus/device_info_plus.dart:63:30)
<asynchronous suspension>
#3      _MyHomePageState._getDeviceId (package:flutter_counter/main.dart:113:23)
<asynchronous suspension>
#4      _MyHomePageState.build.<anonymous closure> (package:flutter_counter/main.dart:91:34)
<asynchronous suspension>
```

it's a pod issue I guess but my knowledge in swift & iOS in general is weak
It will be highly appreciated if you can help me with this

note that this library works fine in android!

thanks in advance

**Comment by huynguyennovem** [comment]
Hey @abdallah-odeh 
I see the issue. In case you add a plugin, please also register plugin to flutter engine. For the details, let's update your `iOSCounterApp.swift` file as below:

```
import FlutterPluginRegistrant
...
init() {
    ...
    GeneratedPluginRegistrant.register(with: self.flutterEngine)
}
```

**Comment by huynguyennovem** [comment]
I just pushed an update, please fetch the latest change and try again. You can check demo here: https://github.com/huynguyennovem/flutter-add-to-app-ios-swiftui/pull/2

**Comment by huynguyennovem** [comment]
I will update the blog post as well. Thanks for filing the issue!

**Comment by abdallah-odeh** [comment]
Thank you for the quick response!

I will try out the new code shortly & tell you the result

**Comment by abdallah-odeh** [comment]
Hello @huynguyennovem 
I tested out the sample project you provided & it works perfectly!
I pumped into another issue & I hope you can help

I also have a native plugin in my app which is `image_cropper`, 
with adding `GeneratedPluginRegistrant.register(with: self.flutterEngine)` it gives the error:
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[SwiftUI.AppDelegate window]: unrecognized selector sent to instance 0x600000c5b1b0' 
once the app appears in the screen and even the native UI does not show up!

but when I remove it, it works fine but the plugin `device_info_plus` fails 

Apologize me, my knowledge in native iOS is weak & I tried to look into it, found nothing :(

thank in advance
